### ISSUE TITLE
2 way sync

### ISSUE THREAD

**Issue by zephirl** [thibaultspriet/SyncNotionCalendar#2]
Would it be possible to have a 2-way synchronisation: when an event is added/modified/deleter in apple calendar then it is reflected in notion as well (and not just the other way around)?

**Comment by thibaultspriet** [comment]
Hi,

I've been thinking about that but I don't want every events from my Apple calendar to be pushed to my Notion database.

However it can be interesting to have a 2-way sync at least for **modifications**

**Comment by ruebyi** [comment]
It could be a great feature if you have an notion only calendar…
