### ISSUE TITLE
main.py script not working

### ISSUE THREAD

**Issue by mattiastofte** [thibaultspriet/SyncNotionCalendar#3]
![image](https://user-images.githubusercontent.com/37273026/151157870-1e82e927-d636-4933-835d-e18d0021143b.png)

**Comment by thibaultspriet** [comment]
Hi !

I've just pushed a fix for it.

Can you pull the repo and try again please. Could you tell me if it's work ?

**Comment by mattiastofte** [comment]
I’ll try tonight:)
